### ISSUE TITLE
File_name null

### ISSUE THREAD

**Issue by ndoulgeridis** [K-Phoen/Vich-Uploader-Sandbox#1]
Hello,

I have installed it but file_name is null when i upload a file.
I think Vich-Uploader-Sandbox-propel-admingen\src\KPhoen\SingleUploadableBundle\Resources\config\vich_uploader\Image.xml is not loaded.... 
Where is this file is called for load? I don't see it in any config file.
 Also file where is not moved after upload to a folder at all?

Thanks a lot.

**Comment by K-Phoen** [comment]
Which branch are you using? I just checked both and all is working fine.

Btw, the `Image.xml` file is automatically loaded by VichUploaderBundle and files are moved to the `web/images` directory (see vich uploader and gaufrette/flysystem config files).

**Comment by ndoulgeridis** [comment]
Hello,

I use master. Hmm probably miss a configuration or something... When i submit the form the file is type of UploadedFile but something fails. It does neither save filename to db (file_name is null) nor move file to the corresponding directory. It doesn't even create directory.

**Comment by K-Phoen** [comment]
You shouldn't need to touch anything in the code in order to make it work (that's the point of the sandbox). That being said, it's not quite finished yet so it may be a bit buggy :)

Is error display in PHP enabled? Even for notices and warnings?
Did you create the project using the composer create-project command? (the one shown in the readme)

**Comment by ndoulgeridis** [comment]
Sorry wrong i use propel_admingen. I saw you did some changes,I am updating latest changes and i will let you know if it works.

**Comment by ndoulgeridis** [comment]
OK updated now and it works! Thanks a lot!!!

**Comment by ndoulgeridis** [comment]
Please if you have some time can you add Avocode and embed form upload with Propel. The Gallery and Image example but with Avocode single or multiple upload.

(In the meantime i will try to achieve it)

**Comment by K-Phoen** [comment]
It's on my todo list (amongst other things) :)
